In [2]:
# Installing Numpy library 
# Import numpy Library

import numpy as np

## Scalar
1. Scalars are One dimentional, primitive datatype and Single Numbers.
2. They are Real or Complex.
3. Scalar variables --> a,b,c,....., x,y,z
4. For ML problems one has to use real values.
5. 2/7 is a scalar value (2/7 --> 0.285714)
6. 30 is a Scalar value

In [3]:
# Scalar
marks = 99
print("The marks achieved are :",marks)


The marks achieved are : 99


## Vector
1. Ordered list of numbers or primitive data types.
2. It is an ordered collection of data.
3. One can perform Addition, Subtraction, Scalar multiplication, Transpose, Inverse and measure how two vectors align
4. The result of dot product of two vectors --> Scalar.
5. Vector can never have negatibve magnitude.
6. The number of Scalars in a vector --> Dimension
7. Vector contains two dimentional array or list.
8. A vector V has dimension of (m,n)
    Where, 
    m = number of rows
    n = number of columns
9. Transpose of V have (n,m) dimension or shape.
10. Column vector --> m rows and 1 column 
                 --> shape is (m,1)
11. Row vector --> 1 row and n columns
                 --> shape is (1,n)
12. Zero Vector --> A vector which contains each element as Zero --> z = [0,0,0]
13. One Vector --> A vector which contains each element as One --> o = [1,1,1]
14. The Magnitude of vector is |V| = $\sqrt{(V1)^2 +(V2)^2 +(V3)^2+ ...... + (Vn)^2}$

In [14]:
# Vector Sum
# 1st Vector is "v1"
# 2nd Vector is "v2"

from numpy import vectorize

def add(v1, v2) -> vectorize:
    """Adds corresponding elements"""
    assert len(v1) == len(v2), "vectors must be the same length"
    return [v1_i + v2_i for v1_i, v2_i in zip(v1, v2)]

v3 = [9, 7, 5]
assert add([3, 2, 1], [6, 5, 4]) == v3
print(f"The Output is correct and it is {v3}")

v4 = [10, 7, 5]
assert add([3, 1], [6, 5, 4]) == v4


The Output is correct and it is [9, 7, 5]


AssertionError: vectors must be the same length

In [19]:
# Vectors : List[vectors]

def vector_sum(vectors):
    """Sums all corresponding elements"""
    # Check that vectors is not empty
    assert vectors, "no vectors provided!"
    # Check the vectors are all the same size
    num_elements = len(vectors[0])
    assert all(len(v) == num_elements for v in vectors), "different sizes!"
    # the i-th element of the result is the sum of every vector[i]
    return [sum(vector[i] for vector in vectors)
        for i in range(num_elements)]
vector = [15, 21]
if vector_sum([[1, 3], [2, 4], [5, 8], [7, 6]]) == vector:
    print(f"The Vector output is {vector}")


The Vector output is [15, 21]


In [8]:
# Transpose of V have (n,m) dimension or shape.

trans = np.array([[4,1,2],[-2,4,8],[6,-3,-5]])

print(" The Column Vector is \n", np.transpose(trans))

 The Column Vector is 
 [[ 4 -2  6]
 [ 1  4 -3]
 [ 2  8 -5]]


In [5]:
#10. Column vector --> m rows and 1 column 
#                --> shape is (m,1)

col_vec = np.array([[4],[-2],[6]])

print(" The Column Vector is \n", col_vec)

# The shape of the column vector
print(" The Shape of the column Vector is ",col_vec.shape)

 The Column Vector is 
 [[ 4]
 [-2]
 [ 6]]
 The Shape of the column Vector is  (3, 1)


In [ ]:
#11. Row vector --> 1 row and n columns
#                 --> shape is (1,n)

row_vec = np.array([4,-2,6])

print(" The Column Vector is \n", row_vec)

# The shape of the column vector
print(" The Shape of the column Vector is ",row_vec.shape)

In [ ]:
# Zero Vector

In [ ]:
# One Vector

In [ ]:
# Magnitude

# Transpose